pg_distrib_dir ='/Users/erik/Projects/neon/pg_install'
broker_endpoint ='http://127.0.0.1:50051/'
control_plane_api ='http://127.0.0.1:1234/upcall/v1/'
remote_storage ={local_path='../local_fs_remote_storage/pageserver'}
listen_pg_addr = "127.0.0.1:64000"
listen_http_addr = "127.0.0.1:9898"
pg_auth_type = "Trust"
http_auth_type = "Trust"
no_sync = true
page_cache_size = 65536
max_file_descriptors = 500000
timeline_offloading = true
ephemeral_bytes_per_memory_kb = 1024

[l0_flush]
mode = "direct"
max_concurrency = 8

[page_service_pipelining]
mode = "pipelined"
execution = "concurrent-futures"
max_batch_size = 32

[get_vectored_concurrent_io]
mode = "sidecar-task"

[wal_receiver_protocol]
type = "interpreted"

[wal_receiver_protocol.args]
format = "protobuf"

[wal_receiver_protocol.args.compression.zstd]
level = 1

